### ISSUE TITLE
Dropdown menus on sanctsound.ioos.us are nearly unreadable 

### ISSUE THREAD

**Issue by MathewBiddle** [noaa-onms/sanctsound#19]
there's something wrong with the tabs (on my computer anyway) - the drop downs are black and if you don't scroll they almost appear empty. Maybe we can change the color scheme?

![image](https://github.com/noaa-onms/sanctsound/assets/8480023/55c41815-53f4-4b28-a803-95be9625747f)

**Comment by bbest** [comment]
Thanks @MathewBiddle! I'm taking a look now

**Comment by bbest** [comment]
And we're back

https://sanctsound.ioos.us/
<img width="1117" alt="image" src="https://github.com/noaa-onms/sanctsound/assets/2837257/415e12f7-e142-47a3-acb3-59e134f677b8">

**Comment by MathewBiddle** [comment]
Thanks @bbest!
